### ISSUE TITLE
scons improvements

### ISSUE THREAD

**Issue by sawjlab** [JeffersonLab/hcana#203]
The top SConscript.py file has a list, "hcheaders", for all the .h files in src.  src/SConscript.py has a list, "list" of all the .cxx files in src.  When a new class is added, both of these files must be updated.  One of these lists should be automatically generated from the other.

Furthermore, it should be possible to avoid hand writing either of these lists.  They could be generating from the file names of all the .cxx files in src.

Even more ideally, the file src/HallC_LinkDef.h which has a line for each class in it, could be generated automatically.  If this is done, then Makefile should also be updated to autogenerate HallC_LinkDef.h and it's source code list "SRC".

**Comment by brash99** [comment]
You may recall that I had implemented all of these suggested fixes a few months ago, and talked about it at one of the software meetings.  I had not done a pull request, because there was the issue of requiring a fairly up-to-date version of scons to make it all work.  I was going to check with Ole about this, and then also check which version was installed on JLab systems, to make sure that was ok as well.  Let me revisit this over the next week, and provided everything is ok, I will do a pull request.

**Comment by sawjlab** [comment]
@brash99 addressed this issues in commit 3840ef25e3e30862e88d76e7b424ac3ba483d5f0
