### ISSUE TITLE
THcPrimaryKine W Calculation

### ISSUE THREAD

**Issue by vargasa** [JeffersonLab/hcana#331]
Hi Guys,

More than an issue it's a question. How are the values for W computed? I track it down to a TLorentzVector but couldn't find the lines. Because I'm getting a bunch of 1e+38 values from the 2397 run replay at cdaql1 `hcana ROOTfiles/coin_replay_production_2397_-1.root.`

![primkine](https://user-images.githubusercontent.com/16821717/36322926-2db6999a-131d-11e8-8c2b-4e943b7f0cdd.png)

**Comment by hansenjo** [comment]
W2 is computed here:

https://github.com/JeffersonLab/hcana/blob/4cb3bfb5fe729b2d924243d02fb7c48954b9f65e/src/THcPrimaryKine.cxx#L181

and W = sqrt(W2) on the next line. It's just the magnitude of the p_recoil = p_target + q four-vector.

1e38 means the value was never computed. Usually that happens when no track was reconstructed for that event in the given spectrometer, or some other essential information is missing. If your run has many garbage triggers, only few events will have valid kinematics. Try plotting W with a sanity cut, for example:
T->Draw("H.kin.primary.W","abs(H.kin.primary.W)<5.")

Ole

**Comment by vargasa** [comment]
Hi Ole, 

Thanks for your email, `W` relays on ` TLorentzVector::Mag2()` that as I understand depends on values of Energy (or time). So I thought such value of W would require a miscalculated energy. When I saw the statistics of the histogram I just get around  ~15 events with valid W and around ~22k events in total. From what you told me can I increase that ratio by suppressing triggers?

**Comment by vargasa** [comment]
Whenever `W` calculation fails `W` is set to `kBig = 1e38`:

https://github.com/JeffersonLab/hcana/blob/5cb1b3eb9132cbbb0e78845fd56a76ca889d4e42/src/THcFormula.cxx#L31

In this particular case, `W` calculation fails because `W2` (W^2)  has negative values. So, In principle we can get only good values of W by setting a cut on W2 to "H.kin.primary.W2>0"

![1](https://user-images.githubusercontent.com/16821717/36392746-b65bc194-157a-11e8-92ab-4e4be584fc4a.png)

That's the closest cut to the one Ole mentioned. @MarkKJones  suggested to apply the following cuts:

`H.cer.npeSum > 1. && H.cal.etracknorm>.5`

Which leaves ~5 events with unresolved W:

![2](https://user-images.githubusercontent.com/16821717/36393096-21745256-157c-11e8-9792-9ae3aa071a58.png)

Combining these two cuts:

`T->Draw("H.kin.primary.W","H.kin.primary.W2>0 && H.tr.n ==1 && H.cer.npeSum > 1. && H.cal.etracknorm>.5")`

We get around ~400 events with good values for `W`

![3](https://user-images.githubusercontent.com/16821717/36393152-66d66b04-157c-11e8-9f82-2d854845b72f.png)

**Comment by hansenjo** [comment]
I guess your W2 has negative (=unphysical) values because the author of the Hall C version of PrimaryKine decided to fix the target mass at M_proton for the W2 calculation. Otherwise I don't know why you'd ever get something negative. W2 is the invariant mass of the struck nuclear recoil system and can only ever be positive. This is real observable matter. If it seems to have more momentum than energy, it's because the initial target 4-vector is wrong and so has, yes, an incorrect (too small) initial rest energy. Someone in Hall A tried passing this exact same ill-defined W2 calculation on me, even implying that I was "doing it wrong." Maybe people should read up on elementary kinematics relations in [Griffith](https://www.amazon.com/Introduction-Elementary-Particles-David-Griffiths/dp/3527406018) or similar. Or explain it to me, cause evidently I must have missed something in grad school. The Hall A PrimaryKine module will give you proper W2, I assure you of that.

**Comment by vargasa** [comment]
Not sure about why. But, actual W2 calculations show negative values

![wn](https://user-images.githubusercontent.com/16821717/36395866-56d646a4-1589-11e8-98ae-5b4159568137.png)
