### ISSUE TITLE
Wrong calculation of multiplicity in THcShowerArray

### ISSUE THREAD

**Issue by sawjlab** [JeffersonLab/hcana#463]
In this line

https://github.com/JeffersonLab/hcana/blob/c420edd53c56a5a9d8db08d317c7f15c82de6d17/src/THcShowerArray.cxx#L908

i think the rhs should be +=1, not = npad + 1

**Comment by MarkKJones** [comment]
This is correct. The variable is NOT a multiplicity. Maybe the name could be better. 

The fNumGoodAdcHits only purpose  is to fill an "occupancy" histogram
which plots the number of good hits in each paddle as a function of paddle. The "+1" is so the paddle ( or block) number
starts at 1 instead of 0. Something similar is done for all detectors to plot their occupancy.
